import {
  SMART_JSON_DISPATCH_MAX_CHARS,
  SMART_JSON_TASK_UNDERSTANDING_MAX_CHARS,
} from '@/lib/office-smart-json-schema';

export const SMART_OUTPUT_SPEC_SECTION_TITLE = '【输出规范·JSON Schema】';

/** 协调者 JSON Schema（与 Smart 协调者提示词第五节一致，仅 role.const 动态）。 */
export function buildSmartCoordinatorJsonSchemaLines(roleName: string): string[] {
  const roleConst = JSON.stringify(roleName);
  return [
    '{',
    '  "type": "object",',
    '  "additionalProperties": false,',
    '  "required": ["role", "inputValidation", "taskUnderstanding", "action", "deliverable", "dispatch"],',
    '  "properties": {',
    '    "role": {',
    `      "const": ${roleConst},`,
    '      "description": "固定为当前协调者角色名，不可修改"',
    '    },',
    '    "inputValidation": {',
    '      "type": "string",',
    '      "description": "验收上一跳交付物时填写完整ls -l结果；无上一跳或无需验收时必须为「无」"',
    '    },',
    '    "taskUnderstanding": {',
    '      "type": "string",',
    `      "maxLength": ${SMART_JSON_TASK_UNDERSTANDING_MAX_CHARS},`,
    '      "description": "简要概括本回合处置目标与依据，2-4句话"',
    '    },',
    '    "action": {',
    '      "type": "string",',
    '      "enum": ["assign", "end"],',
    '      "description": "assign=指派/续派/返工/补交付/验收后续派（需配合dispatch数组）；end=项目所有子任务全部完成，项目结项（此时dispatch必须为[]）"',
    '    },',
    '    "deliverable": {',
    '      "type": "object",',
    '      "additionalProperties": false,',
    '      "required": ["items", "outputValidation"],',
    '      "properties": {',
    '        "items": {',
    '          "type": "array",',
    '          "items": {',
    '            "type": "string",',
    '            "maxLength": 100,',
    '            "description": "交付物相对路径，格式为「交付物-角色名/文件名」（如 交付物-AI-Agent开发专家/xxx-AI-Agent开发专家.md ）；禁止绝对路径、或项目根目录散落文件"',
    '          },',
    '          "description": "协调者本轮自交付物名称数组；无自交付时必须为[]"',
    '        },',
    '        "outputValidation": {',
    '          "type": "array",',
    '          "items": {',
    '            "type": "string",',
    '            "description": "对应items内文件的完整ls -l结果行，格式如「-rw-r--r-- 1 user group 1234 May 20 10:00 filename」"',
    '          },',
    '          "description": "与items一一对应的ls -l结果数组；无自交付时必须为[]"',
    '        }',
    '      }',
    '    },',
    '    "dispatch": {',
    '      "type": "array",',
    '      "items": {',
    '        "type": "object",',
    '        "additionalProperties": false,',
    '        "required": ["role", "task"],',
    '        "properties": {',
    '          "role": {',
    '            "type": "string",',
    '            "description": "任务指派对象，仅限团队成员角色，同一角色不可重复出现"',
    '          },',
    '          "task": {',
    '            "type": "string",',
    `            "maxLength": ${SMART_JSON_DISPATCH_MAX_CHARS},`,
    '            "description": "任务说明需包含目标、输入材料、输出要求、验收标准；落盘路径必须为「交付物-{角色名}/文件名-{角色名}.md」，禁止使用协调者目录"',
    '          }',
    '        }',
    '      },',
    '      "description": "action=assign时至少1项，并行时可多项，但每名成员最多1项；action=end时必须为[]"',
    '    }',
    '  }',
    '}',
  ];
}

/** 成员 JSON Schema（与 Smart 成员提示词第五节一致，仅 role.const 与交付目录示例动态）。 */
export function buildSmartMemberJsonSchemaLines(roleName: string): string[] {
  const role = roleName.trim() || '角色名';
  const roleConst = JSON.stringify(role);
  const dir = `交付物-${role}/`;
  const itemsDescription = `交付物相对路径数组，须落在 ${dir} 下（如 ${dir}xxx-${role}.md）；help 时必须 []；禁止绝对路径、或项目根目录散落文件`;
  return [
    '{',
    '\t"type": "object",',
    '\t"additionalProperties": false,',
    '\t"required": ["role", "taskUnderstanding", "action", "deliverable", "dispatch"],',
    '\t"properties": {',
    '\t\t"role": {',
    `\t\t\t"const": ${roleConst},`,
    '\t\t\t"description": "固定值，不可修改"',
    '\t\t},',
    '\t\t"taskUnderstanding": {',
    '\t\t\t"type": "string",',
    `\t\t\t"maxLength": ${SMART_JSON_TASK_UNDERSTANDING_MAX_CHARS},`,
    '\t\t\t"description": "用2-4句话概括：本次任务的输入资源、核心目标、最终交付成果"',
    '\t\t},',
    '\t\t"action": {',
    '\t\t\t"type": "string",',
    '\t\t\t"enum": ["end", "help"],',
    '\t\t\t"description": "必选；end=本轮任务已完成，向协调者请求验收；help=依赖未就绪/咨询/求助；成员禁止使用 assign"',
    '\t\t},',
    '\t\t"deliverable": {',
    '\t\t\t"type": "object",',
    '\t\t\t"additionalProperties": false,',
    '\t\t\t"required": ["items", "outputValidation"],',
    '\t\t\t"properties": {',
    '\t\t\t\t"items": {',
    '\t\t\t\t\t"type": "array",',
    `\t\t\t\t\t"description": ${JSON.stringify(itemsDescription)},`,
    '\t\t\t\t\t"items": {',
    '\t\t\t\t\t\t"type": "string",',
    '\t\t\t\t\t\t"maxLength": 100',
    '\t\t\t\t\t}',
    '\t\t\t\t},',
    '\t\t\t\t"outputValidation": {',
    '\t\t\t\t\t"type": "array",',
    '\t\t\t\t\t"description": "在项目根目录下对 items内逐项进行ls -l，填写结果；help 时必须 []",',
    '\t\t\t\t\t"items": {',
    '\t\t\t\t\t\t"type": "string"',
    '\t\t\t\t\t}',
    '\t\t\t\t}',
    '\t\t\t}',
    '\t\t},',
    '\t\t"dispatch": {',
    '\t\t\t"type": "array",',
    '\t\t\t"description": "action=end/help 时至少1项，且 role 必须是协调者",',
    '\t\t\t"items": {',
    '\t\t\t\t"type": "object",',
    '\t\t\t\t"additionalProperties": false,',
    '\t\t\t\t"required": ["role", "task"],',
    '\t\t\t\t"properties": {',
    '\t\t\t\t\t"role": {',
    '\t\t\t\t\t\t"type": "string",',
    '\t\t\t\t\t\t"description": "只能填写协调者角色名"',
    '\t\t\t\t\t},',
    '\t\t\t\t\t"task": {',
    '\t\t\t\t\t\t"type": "string",',
    `\t\t\t\t\t\t"maxLength": ${SMART_JSON_DISPATCH_MAX_CHARS},`,
    '\t\t\t\t\t\t"description": "给协调者的处理请求；end 写请验收交付，help 写请排除依赖阻塞/确认上游输入/答疑"',
    '\t\t\t\t\t}',
    '\t\t\t\t}',
    '\t\t\t}',
    '\t\t}',
    '\t}',
    '}',
  ];
}

export function buildSmartMergedOutputSpecLines(
  roleName: string,
  isCoordinator: boolean,
): string[] {
  const schema = isCoordinator
    ? buildSmartCoordinatorJsonSchemaLines(roleName)
    : buildSmartMemberJsonSchemaLines(roleName);
  return [
    SMART_OUTPUT_SPEC_SECTION_TITLE,
    '必须严格输出以下结构的 JSON（仅此 JSON，无 Markdown 包裹外的说明文字）：',
    'json',
    ...schema,
  ];
}
