import { definePluginEntry } from 'openclaw/plugin-sdk/core';
import { isProviderApiKeyConfigured } from 'openclaw/plugin-sdk/provider-auth';
import { resolveApiKeyForProvider } from 'openclaw/plugin-sdk/provider-auth-runtime';
import {
  assertOkOrThrowHttpError,
  postJsonRequest,
  readProviderJsonResponse,
  resolveProviderHttpRequestConfig,
  sanitizeConfiguredModelProviderRequest,
} from 'openclaw/plugin-sdk/provider-http';
import {
  parseOpenAiCompatibleImageResponse,
  resolveInlineImageJsonResponseMaxBytes,
  toImageDataUrl,
} from 'openclaw/plugin-sdk/image-generation';

const PROVIDER_ID = 'clawx-openai-image';
const FALLBACK_MODEL = 'gpt-image-2';
const DEFAULT_BASE_URL = 'https://api.openai.com/v1';
const DEFAULT_SIZE = '1024x1024';
const DEFAULT_OUTPUT_MIME = 'image/png';
const MAX_IMAGE_RESULTS = 4;
const MAX_INPUT_IMAGES = 5;
const DEFAULT_TIMEOUT_MS = 180_000;
const FALLBACK_MAX_IMAGE_BYTES = 6 * 1024 * 1024;
const MB = 1024 * 1024;

/**
 * OpenClaw provider ids that already register an image-generation provider.
 * Never claim these as aliases — doing so would shadow the native providers.
 * Keep in sync with `NATIVE_IMAGE_GENERATION_PROVIDER_IDS` in
 * `electron/utils/openclaw-image-relay-constants.ts` (a unit test asserts this).
 */
const NATIVE_IMAGE_GENERATION_PROVIDER_IDS = new Set([
  'openai',
  'google',
  'minimax',
  'minimax-portal',
  'litellm',
  'comfy',
  'fal',
  'openrouter',
  'vydra',
  'xai',
  'microsoft-foundry',
]);

/**
 * This plugin owns exactly one model family. The model that runs is already
 * fixed by `imageGenerationModel.primary`, so the model id alone decides the
 * wire protocol — nothing is probed. Gemini image models go to
 * `clawx-gemini-image`; other families (minimax `image-01`, Google `imagen-*`,
 * …) are left to OpenClaw's built-in image providers.
 *
 * Keep in sync with `isOpenAiImageModel` in
 * `electron/utils/openclaw-image-relay-constants.ts`.
 */
export function isOpenAiImageModel(modelId) {
  const id = String(modelId ?? '').trim().toLowerCase();
  return id.startsWith('gpt-image') || id.startsWith('dall-e');
}

const SUPPORTED_SIZES = [
  '1024x1024',
  '1536x1024',
  '1024x1536',
  '2048x2048',
  '2048x1152',
  '3840x2160',
  '2160x3840',
];

function trimmedString(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function isRecord(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

/** Model ids declared by a `models.providers` entry (`string[]` or `{id}[]`). */
export function readModelIds(entry) {
  const models = isRecord(entry) ? entry.models : undefined;
  if (!Array.isArray(models)) return [];
  const ids = [];
  for (const model of models) {
    const id = typeof model === 'string' ? trimmedString(model) : trimmedString(isRecord(model) ? model.id : undefined);
    if (id) ids.push(id);
  }
  return ids;
}

/**
 * Provider keys this plugin serves, discovered from config.
 *
 * The keys themselves are generated by `getOpenClawProviderKeyForType`
 * (e.g. `gptimage2-gptimage`), so a plugin cannot know their names ahead of
 * time and must never parse them. We therefore look the other way round: find
 * the entries that host a model of *our* family. The judgement is on model ids,
 * never on key names.
 */
export function collectClaimedProviderKeys(providers) {
  const claimed = new Map();
  for (const [key, entry] of Object.entries(isRecord(providers) ? providers : {})) {
    if (NATIVE_IMAGE_GENERATION_PROVIDER_IDS.has(key.trim().toLowerCase())) continue;
    const familyModels = readModelIds(entry).filter(isOpenAiImageModel);
    if (familyModels.length > 0) claimed.set(key, familyModels);
  }
  return claimed;
}

/** Relay base URLs are stored with or without the `/v1` suffix. */
export function normalizeRelayBaseUrl(value, fallback = DEFAULT_BASE_URL) {
  const trimmed = (trimmedString(value) ?? fallback).replace(/\/+$/u, '');
  if (!trimmed) return DEFAULT_BASE_URL;
  return trimmed.endsWith('/v1') ? trimmed : `${trimmed}/v1`;
}

function resolveCount(req) {
  const raw = Number(req.count ?? 1);
  if (!Number.isFinite(raw)) return 1;
  return Math.max(1, Math.min(MAX_IMAGE_RESULTS, Math.trunc(raw)));
}

function resolveGeneratedImageMaxBytes(cfg) {
  const configured = cfg?.agents?.defaults?.mediaMaxMb;
  if (typeof configured === 'number' && Number.isFinite(configured) && configured > 0) {
    return Math.floor(configured * MB);
  }
  return FALLBACK_MAX_IMAGE_BYTES;
}

function buildProvider(claimed) {
  const aliases = [...claimed.keys()];
  const models = [...new Set([...claimed.values()].flat())];

  return {
    id: PROVIDER_ID,
    aliases,
    label: 'ClawX OpenAI Images',
    defaultModel: models[0] ?? FALLBACK_MODEL,
    models: models.length > 0 ? models : [FALLBACK_MODEL],
    defaultTimeoutMs: DEFAULT_TIMEOUT_MS,
    isConfigured: ({ agentDir }) => aliases.some((key) => isProviderApiKeyConfigured({
      provider: key,
      agentDir,
    })),
    capabilities: {
      generate: {
        maxCount: MAX_IMAGE_RESULTS,
        supportsSize: true,
        supportsAspectRatio: false,
        supportsResolution: false,
      },
      edit: {
        enabled: true,
        maxCount: MAX_IMAGE_RESULTS,
        maxInputImages: MAX_INPUT_IMAGES,
        supportsSize: true,
        supportsAspectRatio: false,
        supportsResolution: false,
      },
      geometry: {
        sizes: [...SUPPORTED_SIZES],
      },
      output: {
        qualities: ['low', 'medium', 'high', 'auto'],
        formats: ['png', 'jpeg', 'webp'],
        backgrounds: ['transparent', 'opaque', 'auto'],
      },
    },
    async generateImage(req) {
      const inputImages = req.inputImages ?? [];
      const isEdit = inputImages.length > 0;
      if (isEdit && inputImages.length > MAX_INPUT_IMAGES) {
        throw new Error(
          `ClawX OpenAI image editing supports up to ${MAX_INPUT_IMAGES} reference images.`,
        );
      }

      // The requested provider key — whatever it is called. Everything below is
      // derived from it, so a regenerated or renamed key needs no code change.
      const providerKey = trimmedString(req.provider) ?? PROVIDER_ID;
      const providerConfig = req.cfg?.models?.providers?.[providerKey];
      if (!isRecord(providerConfig)) {
        throw new Error(
          `ClawX OpenAI image generation has no models.providers entry for "${providerKey}"`,
        );
      }

      const auth = await resolveApiKeyForProvider({
        provider: providerKey,
        cfg: req.cfg,
        agentDir: req.agentDir,
        store: req.authStore,
      });
      if (!auth?.apiKey) throw new Error(`ClawX OpenAI image API key missing for "${providerKey}"`);

      const request = sanitizeConfiguredModelProviderRequest(providerConfig.request);
      const { baseUrl, allowPrivateNetwork, headers, dispatcherPolicy } = resolveProviderHttpRequestConfig({
        baseUrl: normalizeRelayBaseUrl(providerConfig.baseUrl),
        defaultBaseUrl: DEFAULT_BASE_URL,
        // On-prem relays resolve to private IPs; without this the SSRF guard
        // rejects the request outright.
        allowPrivateNetwork: request?.allowPrivateNetwork,
        request,
        defaultHeaders: { Authorization: `Bearer ${auth.apiKey}` },
        provider: providerKey,
        capability: 'image',
        transport: 'http',
      });
      headers.set('Content-Type', 'application/json');

      const model = trimmedString(req.model) ?? FALLBACK_MODEL;
      const count = resolveCount(req);
      const size = req.size ?? DEFAULT_SIZE;
      // Deliberately minimal body: no deprecated response-format field. Natural
      // language can still control OpenAI-native output knobs — quality,
      // output_format, background — which the Images API accepts directly. Each
      // is added only when the caller supplied it, so the default request shape
      // is unchanged and stays maximally relay-compatible. A unit test pins this.
      const body = {
        model,
        prompt: req.prompt,
        n: count,
        size,
        ...(req.quality !== undefined ? { quality: req.quality } : {}),
        ...(req.outputFormat !== undefined ? { output_format: req.outputFormat } : {}),
        ...(req.background !== undefined ? { background: req.background } : {}),
        ...(isEdit
          ? {
            images: inputImages.map((image) => ({
              image_url: toImageDataUrl({ buffer: image.buffer, mimeType: image.mimeType }),
            })),
          }
          : {}),
      };

      const { response, release } = await postJsonRequest({
        url: `${baseUrl}/images/${isEdit ? 'edits' : 'generations'}`,
        headers,
        body,
        timeoutMs: req.timeoutMs ?? DEFAULT_TIMEOUT_MS,
        fetchFn: fetch,
        allowPrivateNetwork,
        ssrfPolicy: req.ssrfPolicy,
        dispatcherPolicy,
      });

      try {
        await assertOkOrThrowHttpError(
          response,
          isEdit ? 'ClawX OpenAI image edit failed' : 'ClawX OpenAI image generation failed',
        );
        const payload = await readProviderJsonResponse(response, `${PROVIDER_ID}.image-generation`, {
          maxBytes: resolveInlineImageJsonResponseMaxBytes(
            MAX_IMAGE_RESULTS,
            resolveGeneratedImageMaxBytes(req.cfg),
          ),
        });
        const images = parseOpenAiCompatibleImageResponse(payload, {
          defaultMimeType: DEFAULT_OUTPUT_MIME,
          fileNamePrefix: 'clawx-image',
          sniffMimeType: true,
          malformedResponseError: isEdit
            ? 'ClawX OpenAI image edit response malformed'
            : 'ClawX OpenAI image generation response malformed',
        });
        if (images.length === 0) {
          throw new Error(isEdit
            ? 'ClawX OpenAI image edit response missing image data'
            : 'ClawX OpenAI image generation response missing image data');
        }
        return { images, model };
      } finally {
        await release();
      }
    },
  };
}

export const pluginEntry = definePluginEntry({
  id: PROVIDER_ID,
  name: 'ClawX OpenAI Image',
  description: 'OpenAI Images (/v1/images/generations) image generation for ClawX-configured relays.',
  register(api) {
    api.registerImageGenerationProvider(buildProvider(collectClaimedProviderKeys(api.config?.models?.providers)));
  },
});

export default pluginEntry;
