export const CLAWX_OPENAI_IMAGE_PROVIDER_KEY = 'clawx-openai-image';
export const CLAWX_OPENAI_IMAGE_DEFAULT_MODEL = 'gpt-image-2';
export const CLAWX_OPENAI_IMAGE_DEFAULT_REF = `${CLAWX_OPENAI_IMAGE_PROVIDER_KEY}/${CLAWX_OPENAI_IMAGE_DEFAULT_MODEL}`;

export const CLAWX_GEMINI_IMAGE_PROVIDER_KEY = 'clawx-gemini-image';

/**
 * OpenClaw provider ids that already register an image-generation provider
 * (each extension's `contracts.imageGenerationProviders`). ClawX image plugins
 * must never claim these as aliases or they would shadow the native providers.
 */
export const NATIVE_IMAGE_GENERATION_PROVIDER_IDS: ReadonlySet<string> = new Set([
  'openai',
  'google',
  'minimax',
  'minimax-portal',
  'litellm',
  'comfy',
  'fal',
  'openrouter',
  'vydra',
  'xai',
  'microsoft-foundry',
]);

/**
 * Model-family predicates — the single source of truth shared by the ClawX
 * prelaunch step and both image plugins.
 *
 * Which image model runs is already decided by `imageGenerationModel.primary`,
 * so the model id alone determines the wire protocol; nothing is probed and no
 * provider key is ever parsed (those keys are generated by
 * `getOpenClawProviderKeyForType` and must not be treated as a contract).
 *
 * The two families are disjoint and both are positive matches: anything else
 * (minimax `image-01`, Google `imagen-*`, …) is intentionally left to
 * OpenClaw's own built-in image providers.
 */
export function isGeminiImageModel(modelId: string): boolean {
  const id = modelId.trim().toLowerCase();
  return id.includes('gemini') && id.includes('image');
}

export function isOpenAiImageModel(modelId: string): boolean {
  const id = modelId.trim().toLowerCase();
  return id.startsWith('gpt-image') || id.startsWith('dall-e');
}

/**
 * The ClawX image plugin that owns `modelId`, or null when the model belongs to
 * a family OpenClaw already handles natively.
 */
export function resolveClawXImagePluginId(modelId: string): string | null {
  if (isGeminiImageModel(modelId)) return CLAWX_GEMINI_IMAGE_PROVIDER_KEY;
  if (isOpenAiImageModel(modelId)) return CLAWX_OPENAI_IMAGE_PROVIDER_KEY;
  return null;
}
