/**
 * Pure resolution of which ClawX image-generation plugins a config needs, plus
 * the config write that enables them.
 *
 * Kept free of electron-dependent modules (no `electron/gateway/config-sync.ts`
 * imports) so it can be unit tested directly, mirroring how
 * `config-sync-env.ts` isolates `stripSystemdSupervisorEnv` from the rest of
 * `config-sync.ts`.
 */
import { readOpenClawConfig, writeOpenClawConfig } from '../utils/channel-config';
import { withConfigLock } from '../utils/config-mutex';
import { NATIVE_IMAGE_GENERATION_PROVIDER_IDS, resolveClawXImagePluginId } from '../utils/openclaw-image-relay-constants';

/** Every image-generation model ref the config asks for (defaults + per-agent). */
export function collectImageGenerationModelRefs(config: unknown): string[] {
  const refs: string[] = [];
  const push = (value: unknown): void => {
    if (typeof value === 'string') {
      if (value.trim()) refs.push(value.trim());
      return;
    }
    if (!value || typeof value !== 'object') return;
    const slot = value as { primary?: unknown; fallbacks?: unknown };
    if (typeof slot.primary === 'string' && slot.primary.trim()) refs.push(slot.primary.trim());
    if (Array.isArray(slot.fallbacks)) {
      for (const fallback of slot.fallbacks) {
        if (typeof fallback === 'string' && fallback.trim()) refs.push(fallback.trim());
      }
    }
  };

  if (!config || typeof config !== 'object') return refs;
  const agents = (config as { agents?: unknown }).agents;
  if (!agents || typeof agents !== 'object') return refs;
  push((agents as { defaults?: { imageGenerationModel?: unknown } }).defaults?.imageGenerationModel);
  const list = (agents as { list?: unknown }).list;
  if (Array.isArray(list)) {
    for (const entry of list) {
      if (entry && typeof entry === 'object') {
        push((entry as { imageGenerationModel?: unknown }).imageGenerationModel);
      }
    }
  }
  return refs;
}

/**
 * ClawX image plugins the current config needs, plus the `models.providers`
 * keys that back them.
 *
 * A ref only needs a ClawX plugin when its provider is a `models.providers`
 * entry that no native OpenClaw image provider backs. Which plugin is decided
 * by the ref's model id alone (`resolveClawXImagePluginId`) — the provider key
 * is generated by `getOpenClawProviderKeyForType` and is never parsed here.
 * Families OpenClaw handles natively (minimax `image-01`, `imagen-*`, …) return
 * no plugin. `providerKeys` are the account entries whose credentials/baseUrl
 * the plugins resolve at request time.
 */
export function resolveRequiredClawXImagePlugins(rawConfig: unknown): {
  pluginIds: string[];
  providerKeys: string[];
} {
  const providers = (rawConfig as { models?: { providers?: Record<string, unknown> } } | null)
    ?.models?.providers;
  const pluginIds = new Set<string>();
  const providerKeys = new Set<string>();

  for (const ref of collectImageGenerationModelRefs(rawConfig)) {
    const slash = ref.indexOf('/');
    if (slash <= 0 || slash >= ref.length - 1) continue;
    const providerKey = ref.slice(0, slash).trim();
    const modelId = ref.slice(slash + 1).trim();
    if (!providerKey || !modelId) continue;
    if (NATIVE_IMAGE_GENERATION_PROVIDER_IDS.has(providerKey.toLowerCase())) continue;
    if (!providers || typeof providers !== 'object' || !providers[providerKey]) continue;
    const pluginId = resolveClawXImagePluginId(modelId);
    if (pluginId) {
      pluginIds.add(pluginId);
      providerKeys.add(providerKey);
    }
  }

  return { pluginIds: [...pluginIds].sort(), providerKeys: [...providerKeys].sort() };
}

/** Convenience wrapper: just the plugin ids the config needs. */
export function resolveRequiredClawXImagePluginIds(rawConfig: unknown): string[] {
  return resolveRequiredClawXImagePlugins(rawConfig).pluginIds;
}

/**
 * Enable the ClawX image plugins the config needs, pin
 * `mediaGenerationAutoProviderFallback` off, and ensure each backing provider
 * entry allows private-network access.
 *
 * Without the fallback flag OpenClaw appends every authenticated provider's
 * default image model as a fallback candidate (`resolveCapabilityModelCandidates`),
 * so a model the relay cannot serve would silently render through an unrelated
 * provider instead of failing.
 *
 * `request.allowPrivateNetwork` is required because on-prem relays resolve to
 * internal IPs that the SSRF guard rejects by default; account entries that
 * never went through `ensureOpenClawProviderAllowPrivateNetwork` (e.g. a fresh
 * image account) would otherwise be blocked. `providerKeys` are the entries
 * actually referenced by an `imageGenerationModel` ref for these plugins.
 */
export async function ensureClawXImagePluginConfig(
  pluginIds: string[],
  providerKeys: string[] = [],
): Promise<void> {
  if (pluginIds.length === 0) return;
  await withConfigLock(async () => {
    const config = await readOpenClawConfig();
    if (!config.plugins) config.plugins = {};
    config.plugins.enabled = true;

    const allow = Array.isArray(config.plugins.allow)
      ? config.plugins.allow.filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0)
      : [];
    const nextAllow = [...allow];
    for (const pluginId of pluginIds) {
      if (!nextAllow.includes(pluginId)) nextAllow.push(pluginId);
    }
    config.plugins.allow = nextAllow;

    if (!config.plugins.entries || typeof config.plugins.entries !== 'object') {
      config.plugins.entries = {};
    }
    for (const pluginId of pluginIds) {
      const entry = config.plugins.entries[pluginId] || {};
      entry.enabled = true;
      config.plugins.entries[pluginId] = entry;
    }

    const providers = (config.models && typeof config.models === 'object'
      ? (config.models as { providers?: unknown }).providers
      : undefined);
    if (providers && typeof providers === 'object') {
      for (const providerKey of providerKeys) {
        const entry = (providers as Record<string, unknown>)[providerKey];
        if (!entry || typeof entry !== 'object') continue;
        const providerEntry = entry as Record<string, unknown>;
        const request = (providerEntry.request && typeof providerEntry.request === 'object'
          ? providerEntry.request
          : {}) as Record<string, unknown>;
        request.allowPrivateNetwork = true;
        providerEntry.request = request;
      }
    }

    const agents = (config.agents && typeof config.agents === 'object'
      ? config.agents
      : {}) as Record<string, unknown>;
    const defaults = (agents.defaults && typeof agents.defaults === 'object'
      ? agents.defaults
      : {}) as Record<string, unknown>;
    defaults.mediaGenerationAutoProviderFallback = false;
    agents.defaults = defaults;
    config.agents = agents;

    await writeOpenClawConfig(config);
  });
}
